version: '2'
services:
    postgresql-hackaton:
        container_name: postgresql-hackaton
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 1950:5432
